### ISSUE TITLE
correlated t-test tutorial misunderstanding 

### ISSUE THREAD

**Issue by daminier** [BayesianTestsML/tutorial#3]
Hi everyone, 
I am just wondering if the variable "names" is wrongly labelled in this tutorial: tutorial/Python/Correlated t-test for comparing classifiers performance on the same dataset
**Aren't they reversed?** 
<img width="955" alt="schermata 2018-12-18 alle 14 55 22" src="https://user-images.githubusercontent.com/15062047/50162018-301ce380-02d5-11e9-9f35-e32a04564d92.png">

**Comment by janezd** [comment]
It sure looks like. The output that follows is also wrong -- it suggests that nbc is (most probably) better than AODE, which is (most probably) wrong. :) @benavoli, can you check and fix?

By the way, here's our more recent library for these tests in Python: https://github.com/janezd/baycomp (docs: https://baycomp.readthedocs.io/en/latest/).

**Comment by daminier** [comment]
> It sure looks like. The output that follows is also wrong -- it suggests that nbc is (most probably) better than AODE, which is (most probably) wrong. :) @benavoli, can you check and fix?
> 
> By the way, here's our more recent library for these tests in Python: https://github.com/janezd/baycomp (docs: https://baycomp.readthedocs.io/en/latest/).

Thank you!

**Comment by benavoli** [comment]
Thanks Enrico, I will fix it.

**Comment by skylogic004** [comment]
I was confused by this too. So I fixed it and created a pull request.
